### ISSUE TITLE
미니 프로젝트 기능 구상

### ISSUE THREAD

**Issue by dan22200252** [2023OSSLTeam15/2023OSSL_miniProject#1]
한동대생 출석 교회 현황

- [ ] 교회 이름, 교회 주소, 청년부 예배 시작 시간에 관한 기본 CRUD 기능 구현
- [ ] 매주 일요일 오늘 방문할 교회 선택 시 각 주 방문한 한동대학교 학생 수 +1
- [ ] 일요일이 아닌 요일에 위 메뉴 선택 시 오류 메세지 출력
- [ ] 각 주 방문한 한동대학교 학생 수 출력 기능 구현
- [ ] 각 달 교회 출석 현황 볼 수 있는 기능 구현
- [ ] 교회 리스트 출력 시 조회수가 높은 순서대로 출력 & 가장 많은 사람이 출석한 교회 이름 하단에 출력
- [ ] 오늘의 추천 교회 게임 기능 구현

**Comment by dan22200252** [comment]
커밋 메세지 양식 정하고 하나로 통일시킬 것

- 한국어로?
- 생성
- 삭제
- 파일 이름 변경
- 변수 이름 변경

**Comment by oss22200250** [comment]
> 한동대생 출석 교회 현황
> 
> * [ ]  교회 이름, 교회 주소, 청년부 예배 시작 시간에 관한 기본 CRUD 기능 구현 
> * [ ]  매주 일요일 오늘 방문할 교회 선택 시 각 주 방문한 한동대학교 학생 수 +1 
> * [ ]  일요일이 아닌 요일에 위 메뉴 선택 시 오류 메세지 출력 
> * [ ]  각 주 방문한 한동대학교 학생 수 출력 기능 구현 
> * [ ]  각 달 교회 출석 현황 볼 수 있는 기능 구현
> * [ ]  교회 리스트 출력 시 조회수가 높은 순서대로 출력 & 가장 많은 사람이 출석한 교회 이름 하단에 출력
> * [ ]  오늘의 추천 교회 게임 기능 구현

모두 완료!

**Comment by oss22200250** [comment]
> 
구조체 및 함수 구현.
커밋 메시지 양식 정하고 통일.
